#define VERSION "0.1.0"
#define HAVE_STDBOOL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDIO_H 1
#define HAVE_ERR_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_NETDB_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_PWD_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_ERRNO_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_CTYPE_H 1
#define HAVE_FCNTL_H 1
#define HAVE_WORDEXP_H 1
